### ISSUE TITLE
BS does not post command file to web page

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/livedata#47]
Re(run_command_file()) does not seem to post copy of command file to our web page: 
https://usaxslive.xray.aps.anl.gov/specmacro.txt

This is issue when running:
1. BS directly using Re(run_command_file())
2. Using BS to run remote operations mode.

**Comment by prjemian** [comment]
To view the new content in the file labeled `specmacro.txt` on the *livedata* page, I had to refresh my browser cache.

This entire process is suffering from diversion from the original design (at 33id or 32id).  Since the code is Py2.7 and Py3.8 is current release, we should revise the *livedata* process completely to rely on the design of the [pvwebmonitor](https://github.com/prjemian/pvWebMonitor) package for the handling of the public web site.  The new livedata would be responsible only for maintain the local www directory (which is copied to the public site).
